/***************************************************************************
*               Generated by StarUML(tm) C++ Add-In                        *
***************************************************************************/
/***************************************************************************
*                                                                          *
*           Institute of Industrial and Control Engineering                *
*                 Technical University of Catalunya                        *
*                        Barcelona, Spain                                  *
*                                                                          *
*                Project Name:       Kautham Planner                       *
*                                                                          *
*     Copyright (C) 2007 - 2009 by Alexander Pérez and Jan Rosell          *
*            alexander.perez@upc.edu and jan.rosell@upc.edu                *
*                                                                          *
*             This is a motion planning tool to be used into               *
*             academic environment and it's provided without               *
*                     any warranty by the authors.                         *
*                                                                          *
*          Alexander Pérez is also with the Escuela Colombiana             *
*          de Ingeniería "Julio Garavito" placed in Bogotá D.C.            *
*             Colombia.  alexander.perez@escuelaing.edu.co                 *
*                                                                          *
***************************************************************************/
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
 
 

#if !defined(_MLLOCALPLANNER_H)
#define _MLLOCALPLANNER_H

#include <libproblem/workspace.h>
#include <libsampling/sampling.h>
#include "localplanner.h"

using namespace libProblem;

namespace libPlanner {
      typedef std::pair<KthReal, KthReal> thumbLimits;

class ManhattanLikeLocalPlanner:public LocalPlanner {
    public:
      ManhattanLikeLocalPlanner(SPACETYPE stype, Sample *init, Sample *goal, WorkSpace *ws, KthReal st );
      void setMethod(bool vandercorput = true);
      bool canConect();
	  bool canConect(Sample *init, Sample *goal);
      KthReal distance(Sample* from, Sample* to);
      inline Sample* initSamp2(){return _init2;};
      inline Sample* goalSamp2(){return _goal2;};
	  void setIntermediateConfs();

	  
	  inline void setSamplesPtr(SampleSet* s){_samp = s;};
	  inline void setThumbDataPtr(vector<thumbLimits*> *th){_thumb = th;};
    private:
      ManhattanLikeLocalPlanner();
      bool vanderMethod;
      Sample* _init2;
      Sample* _goal2;
	  SampleSet* _samp;
	  vector<thumbLimits*> *_thumb;
	};
}

#endif  //_MLLOCALPLANNER_H

