// Do not edit this file. It is automatically generated by the cmake.
// The version number of Kautham has to be set in the CMakeList.txt file.
#define MAJOR_VERSION 3
#define MINOR_VERSION 0
#define PATCH_VERSION 0

